export { cloudinaryPlugin } from './cloudinary'
export { previewPlugin } from './preview'
export { settingsPlugin } from './settings'
export { navPlugin } from './nav'
export { i18nPlugin } from './i18n'