query Post($slug: String, $draft: Boolean = false, $locale: LocaleInputType) {
  Posts(draft: $draft, locale: $locale, limit: 1, where: { slug: { equals: $slug } }) {
    docs {
      ...PostFragment
    }
  }
}

query AllPosts($draft: Boolean = false, $locale: LocaleInputType) {
  Posts(draft: $draft, locale: $locale) {
    docs {
      ...PostFragment
    }
  }
}

fragment PostFragment on Post {
  id
  title
  content
  _status
  slug
  blocks {
    __typename
    ... on QuoteBlock {
      quoteHeader
      quoteText
    }
  }
  image {
    ...MediaFragment
  }
}
