import '@/styles/index.scss'
import s from './layout.module.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const runtime = 'edge'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={s.body}>{children}</body>
    </html>
  )
}
